version: '3.8'

services:
  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asd112233
      POSTGRES_DB: blog_test
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DB_USERNAME : postgres
      DB_PASSWORD : Asd112233
      NODE_ENV : test
      DB_HOST : postgres
      DB_PORT : 5432
      DB_NAME : blog_test
    ports:
      - "3001:5000"
    depends_on:
      - postgres

volumes:
  postgres-data: {}


