version: '3.8'

services:
  app:
    container_name: app-p
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    depends_on:
      - postgres
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: Asd112233
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: blog

  postgres:
    container_name: db-p
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asd112233
      POSTGRES_DB: blog
    ports:
        - "5440:5432"
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
      #- type: tmpfs
       # target: /var/lib/postgresql/data
       # tmpfs:
       #   size: 100m
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data-prod: {}
