version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5000:3000"
    depends_on:
      - postgres
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: Asd112233
      NODE_ENV: test
      DB_HOST: postgres
      DB_PORT: 5432
      DB_TEST_NAME: blog_test

  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asd112233
      POSTGRES_DB: blog_test
    ports:
      - "5440:5432"
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
      #- type: tmpfs
        #target: /var/lib/postgresql/data
        #tmpfs:
          #size: 100m
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data-test: {}
